# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 23:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=50)),
                ('avatar', models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='media/profiles/')),
                ('activation_key', models.CharField(blank=True, max_length=50, null=True)),
                ('key_expires', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'administrators',
                'verbose_name_plural': 'administradores',
                'verbose_name': 'administrador',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'categories',
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=50)),
                ('avatar', models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='media/profiles/')),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=8)),
                ('activation_key', models.CharField(blank=True, max_length=50, null=True)),
                ('key_expires', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'customers',
                'verbose_name_plural': 'Customers',
                'verbose_name': 'Customer',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('available', models.BooleanField()),
            ],
            options={
                'db_table': 'mesas',
                'verbose_name_plural': 'Mesas',
                'verbose_name': 'Mesa',
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=8)),
                ('menu_path', models.FilePathField()),
            ],
            options={
                'db_table': 'negocios',
                'verbose_name_plural': 'Negocios',
                'verbose_name': 'Negocio',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.Category')),
            ],
            options={
                'db_table': 'products',
                'verbose_name_plural': 'Products',
                'verbose_name': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('flyer', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField()),
                ('valid_since', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.Negocio')),
            ],
            options={
                'db_table': 'promotions',
                'verbose_name_plural': 'Promotions',
                'verbose_name': 'Promotion',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('delivered_address', models.CharField(max_length=200)),
                ('stored_by', models.CharField(max_length=100)),
                ('delivered', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.Customer')),
            ],
            options={
                'db_table': 'requests',
                'verbose_name_plural': 'Pedidos',
                'verbose_name': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='request_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.Product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.Request')),
            ],
            options={
                'db_table': 'request_details',
                'verbose_name_plural': 'detalle_pedidos',
                'verbose_name': 'detalle_pedido',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('customer_quantity', models.IntegerField()),
                ('expired', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.Customer')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.Negocio')),
            ],
            options={
                'db_table': 'reservations',
                'verbose_name_plural': 'Reservations',
                'verbose_name': 'Reservation',
            },
        ),
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('storage', models.FloatField()),
            ],
            options={
                'db_table': 'suscriptions',
                'verbose_name_plural': 'Suscriptions',
                'verbose_name': 'Suscription',
            },
        ),
        migrations.AddField(
            model_name='request',
            name='details',
            field=models.ManyToManyField(through='publicidad.request_details', to='publicidad.Product'),
        ),
        migrations.AddField(
            model_name='request',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.Negocio'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='suscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.Suscription'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.Negocio'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicidad.Negocio'),
        ),
    ]
