# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0003_auto_20160721_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='negocio',
        ),
        migrations.AlterField(
            model_name='negocio',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='publicidad.Administrator'),
        ),
    ]
