# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 02:07
from __future__ import unicode_literals
from django.db import migrations
from django.contrib.auth.models import Group, Permission


def add_admin_group(apps, schema_editor):

    group, created = Group.objects.get_or_create(name='Administrator')

    if created:
        # get permission needed and then asign it to the group
        # manage account and negocio related perms
        edit_negocio = Permission.objects.get(codename='change_negocio')
        edit_admin = Permission.objects.get(codename='change_administrator')

        # products perms
        new_product = Permission.objects.get(codename='add_product')
        edit_product = Permission.objects.get(codename='change_product')
        del_product = Permission.objects.get(codename='delete_product')

        # category perms
        new_cate = Permission.objects.get(codename='add_category')
        edit_cate = Permission.objects.get(codename='change_category')
        del_cate = Permission.objects.get(codename='delete_category')

        # promotions perms
        new_promo = Permission.objects.get(codename='add_promotion')
        edit_promo = Permission.objects.get(codename='change_promotion')
        del_promo = Permission.objects.get(codename='delete_promotion')

        # mesa perms (aka table)
        new_mesa = Permission.objects.get(codename='add_mesa')
        edit_mesa = Permission.objects.get(codename='change_mesa')
        del_mesa = Permission.objects.get(codename='delete_mesa')

        # requests perms
        new_req = Permission.objects.get(codename='add_request')
        edit_req = Permission.objects.get(codename='change_request')
        del_req = Permission.objects.get(codename='delete_request')

        # reservations perms
        new_res = Permission.objects.get(codename='add_reservation')
        edit_res = Permission.objects.get(codename='change_reservation')
        del_res = Permission.objects.get(codename='delete_reservation')

        group.permissions.add(edit_negocio,
                              edit_admin,
                              new_product,
                              edit_product,
                              del_product,
                              new_cate,
                              edit_cate,
                              del_cate,
                              new_promo,
                              edit_promo,
                              del_promo,
                              new_mesa,
                              edit_mesa,
                              del_mesa,
                              new_req,
                              edit_req,
                              del_req,
                              new_res,
                              edit_res,
                              del_res)
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0004_auto_20160802_1419'),
    ]

    operations = [
        migrations.RunPython(add_admin_group)
    ]
