# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0005_auto_20160805_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicidad.Negocio'),
        ),
    ]
